name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      # ワークフロー開始時に自動生成される GITHUB_TOKEN との競合を防ぐために、使用するトークンを明示的に指定
      # GITHUB_TOKEN：https://docs.github.com/ja/actions/security-guides/automatic-token-authentication
      # 個人用アクセストークン：https://docs.github.com/ja/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
      with:
        token: ${{ secrets.ACTIONS_PAT }}

    # Gitのセットアップ
    - name: Setup Git
      run: |
        git config user.name "tutti-hobbyist"
        git config user.email "tutti.hobbyist@gmail.com"

    # Pythonのセットアップ
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
      

    # Pythonファイルの実行
    - name: Run Python
      run: |
        python make-install-script.py

    # 実行した結果をプッシュして変更をレポジトリに反映
    - name: Commit and Push changes
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      # 作業ツリーに変更がない場合はプッシュをスキップ、変更がある場合にのみ、コミットとプッシュを実行
      run: |
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          echo "Changes detected:"
          git diff --cached
          git commit -m "automatic update by GitHub Actions"
          git pull origin main
          git push https://${{ secrets.ACTIONS_PAT }}@github.com/tutti-hobbyist/vscode-extensions.git main
        fi