name: generate

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  automatic-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Run Python
        run: python make-install-script.py